import random
import sys
import time
from art import *

# header art
header = text2art("smile")
print(header)
print("by lucy tran")

# defining speed of text
typing_speed = 80
def slow_type(msg):
    for letter in msg:
        sys.stdout.write(letter)
        sys.stdout.flush()
        time.sleep(random.random()*8.0/typing_speed)
    return ''

def slow_type2(msg):
    for letter in msg:
        sys.stdout.write(letter)
        sys.stdout.flush()
        time.sleep(random.random()*5.0/typing_speed)
    return ''

def delete_last_line():
    "Use this function to delete the last line in the STDOUT"

    #cursor up one line
    sys.stdout.write('\x1b[1A')

    #delete last line
    sys.stdout.write('\x1b[2K')

if __name__ == "__main__":
    print(".....")
    time.sleep(5.5)
    delete_last_line()

# game starting -- player must answer yes or it will end
answer = input(slow_type("\nWake up?: "))
if answer.lower().strip() == "yes":
	slow_type2(".....")
	time.sleep(3)
	delete_last_line()

#plot introduction
	slow_type("\nI could feel a sharp pain on the left side of my head-- and the light was not helping at all.")
	time.sleep(2)
	slow_type("\nSlowly, I started to open my eyes because there was a bright fluorescent light shining onto my face directly. I should really move that somewhere the next time I decide to sleep on the couch.")
	time.sleep(3)
	slow_type2("\nWait a minute, couch?")
	time.sleep(2)
	slow_type2("\nI look down and see that I'm resting on a plaid sofa. My eyes wander around the room and I can easily identify my surroundings-- there's a few study rooms, a couple of bookshelves here and there, glass windows, and a bunch of empty seats. \nI guess I fell asleep at school.. but why's no one here?")
	time.sleep(2)

# path no.1

	if answer == "yes":
		answer = input(slow_type("\nShould I get up? (Yes/No): ")).lower().strip()
		slow_type2("\n God, my head hurts so fucking much. I can't believe no one woke me up, but at least it's not dark out yet.")
	
	#1a	
		answer = input(slow_type2("\nWhere should I go though? \n 1- Go to the attendance office. \n 2- Go to your favorite teacher's room. Mr. Lin's always at school anyway. \n 3- Go to the bathroom. I really need to pee. \n 4- I'll just go home now. I don't like school anyway. \n")).lower().strip()	
		if answer == '1' or answer == '2' or answer == '3' or answer == '4':
			slow_type2("\n(Time to go, I guess. It's gonna be dark soon so I better go quickly.)")
			time.sleep(4)
			slow_type2("\n.....")
			time.sleep(3)
			slow_type("\nThe moment I even started to get up from the couch, my legs gave out. It felt like someone was pushing down on my knees and not letting me get up. \nOh well, it's fine. My head hurts anyway and I just woke up so it's probably just the fact that I'm still pretty tired. I'll get up in a few minutes.\nLooking out at the large windows, I immediately noticed one thing: the school was deserted. Usually there's random kids playing badminton in front of the building or a fundraiser happening-- especially if it's still bright out.. Where is everyone?")
			time.sleep(6)
			slow_type("\nI tried to get up once more, but I couldn't.")
			time.sleep(3)
			slow_type("\nI tried again, but I couldn't. \nThe sun has already started to set, and I can't get up.")
			time.sleep(2)
			slow_type2("\nMe: I just want to go home now.. Why can't I move..?' \nFeeling helpless, I bursted into tears. I couldn't find my phone or laptop or anything at all. I was trapped in school and I couldn't get up-- no one would be at school anymore.")
			time.sleep(4)
			slow_type("\n???: Hey, don't cry!")
			time.sleep(4)
			slow_type("\nHuh..? Who was that?")
			time.sleep(4)
			slow_type("\nI can hear footsteps from far away getting closer...")
			time.sleep(2.5)

# sudden character interaction
			answer = input(slow_type("\nHuh..? Who is that.. What do I do..?\n1-Call for help! He could be one of the student advisors/security. \n2-Try to get up and hide. \n3-Stop crying.\n")).lower().strip()
		
			if answer== "1":
				slow_type2("\n'Help! I've been stuck here but I can't get up!'")
				slow_type("\nThe footsteps become louder and I can now see the man who told me to not cry. \nA tall caucasian man emerged from the darkness of the Student Union Cafe and walked towards me, smiling. He held a Nikon camera in his hands and carried a big bright smile on his face. I don't recognize him, but then again, I've never really bothered trying to meet staff anyway. \nHe started to walk towards me, and then he stood in front of the giant windows in front of me.")
				time.sleep(3.5)
				slow_type2("\n???: Ah I see.. But first...")
				time.sleep(2)
				slow_type("\nHe wiped away my tears and grinned brightly.")
				time.sleep(2)
				slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
				time.sleep(3)
				slow_type("\nAlthough he wiped the tears from my face, I felt more rushing out. Even though I started crying once again, he angled his camera down and took photos of me in every angle. I feel uncomfortable.")

				answer = input(slow_type("\nShould I... \n1-Ask him to stop. \n2-Ask him who he is. \n3-Ask him to help me up. \n")).lower().strip()
				if answer == '1' or answer == '2' or answer == '3':
					slow_type("\nI wipe away my tears mid-photo and open my mouth to ask him a question, but for some reason, I can't say anything at all.")
					time.sleep(3)
					slow_type("\nI can't get up. I can't talk. I can't stop crying. \nAnd all he's doing is taking my photograph..")
					time.sleep(6.5)
					slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
					time.sleep(5)
					slow_type("\nHe put his camera down, smiled, and then just left.")
					time.sleep(6)
					slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
					time.sleep(4)
					slow_type2("\n.....")
					time.sleep(8.5)

	# new plot "introduction"

					if __name__ == "__main__":
					    print(".....")
					    time.sleep(3)
					    delete_last_line()

					# game starting
					answer = input(slow_type("Wake up...?: "))
					if answer.lower().strip() == "yes":
						slow_type2("\n.....")
						time.sleep(3)
						delete_last_line()
						slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
						time.sleep(2)
						slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
						time.sleep(3)
						slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
						time.sleep(5.5)
						slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
						time.sleep(3)
						slow_type2("\n.....")
						time.sleep(3)
						slow_type2("\nOh, my ex just texted me.")
						
						answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
						if answer== "yes" or answer == "no":
							slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
							time.sleep(7)
							slow_type("\nSuddenly, my door flew open.")
							time.sleep(2)
							slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
							time.sleep(3)
							slow_type("\n.....")
							time.sleep(3)
							slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
							time.sleep(3)
							slow_type2("\n'Who are you?! Why are you in my room?!'")
							time.sleep(4)
							slow_type2("\n???: Hey, don't cry!")
							time.sleep(3)
							slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
							time.sleep(4)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(2)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(5)
							slow_type("\n Hey.. why can't... I yell...?")
							time.sleep(2)
							slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
							time.sleep(4)
							slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
							time.sleep(5)
							slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
							time.sleep(5)
							slow_type("\nHe put his camera down, smiled, and then just left.")
							time.sleep(6)
							slow_type2("\n.....")
							time.sleep(8.5)

	# game "starting" again
							answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
							if answer == "yes" or answer == "no":
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
							else:
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
						

					else:
						slowtype("I don't wanna wake up.. I'm scared...")
				
				else:
					slow_type("\nI wipe away my tears mid-photo and sit in silence. I feel too uncomfortable to speak.")
					time.sleep(3)
					slow_type("\nI can't get up. I can't stop crying. \nAnd all he's doing is taking my photograph..")
					time.sleep(6.5)
					slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
					time.sleep(5)
					slow_type("\nHe put his camera down, smiled, and then just left.")
					time.sleep(7)
					slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
					time.sleep(4)
					slow_type("\n.....")
					time.sleep(8.5)

				# new plot "introduction"

					if __name__ == "__main__":
					    print(".....")
					    time.sleep(3)
					    delete_last_line()

				# game starting
					answer = input(slow_type("Wake up...?: "))
					if answer.lower().strip() == "yes":
						slow_type2("\n.....")
						time.sleep(3)
						delete_last_line()
						slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
						time.sleep(2)
						slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
						time.sleep(3)
						slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
						time.sleep(5.5)
						slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
						time.sleep(3)
						slow_type2("\n.....")
						time.sleep(3)
						slow_type2("\nOh, my ex just texted me.")
						
						answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
						if answer== "yes" or answer == "no":
							slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
							time.sleep(7)
							slow_type("\nSuddenly, my door flew open.")
							time.sleep(2)
							slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
							time.sleep(3)
							slow_type("\n.....")
							time.sleep(3)
							slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
							time.sleep(3)
							slow_type2("\n'Who are you?! Why are you in my room?!'")
							time.sleep(4)
							slow_type2("\n???: Hey, don't cry!")
							time.sleep(3)
							slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
							time.sleep(4)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(2)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(5)
							slow_type("\n Hey.. why can't... I yell...?")
							time.sleep(2)
							slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
							time.sleep(4)
							slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
							time.sleep(5)
							slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
							time.sleep(5)
							slow_type("\nHe put his camera down, smiled, and then just left.")
							time.sleep(6)
							slow_type2("\n.....")
							time.sleep(8.5)

			# game "starting" again
							answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
							if answer == "yes" or answer == "no":
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
							else:
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")

					else:
						slowtype("I don't wanna wake up.. I'm scared...")
					

		# 2a

			if answer == "2":
				slow_type("I try once more to get up, but to no avail. The footsteps are already getting closer..")
				time.sleep(2)
				slow_type("\nA tall caucasian man emerged from the darkness of the Student Union Cafe and walked towards me, smiling. He held a Nikon camera in his hands and carried a big bright smile on his face. I don't recognize him, but then again, I've never really bothered trying to meet staff anyway. \nHe started to walk towards me, and then he stood in front of the giant windows in front of me.")
				time.sleep(3.5)
				slow_type2("\n???: Hey, what'd I say? Don't cry, smile!")
				time.sleep(2)
				slow_type("\nHe wiped away my tears and grinned brightly.")
				time.sleep(2)
				slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
				time.sleep(3)
				slow_type("\nAlthough he wiped the tears from my face, I felt more rushing out. Even though I started crying once again, he angled his camera down and took photos of me in every angle. I feel uncomfortable.")

				answer = input(slow_type("\nShould I... \n1-Ask him to stop. \n2-Ask him who he is. \n3-Ask him to help me up. \n")).lower().strip()
				if answer == '1' or answer == '2' or answer == '3':
					slow_type("\nI wipe away my tears mid-photo and open my mouth to ask him a question, but for some reason, I can't say anything at all.")
					time.sleep(3)
					slow_type("\nI can't get up. I can't talk. I can't stop crying. \nAnd all he's doing is taking my photograph..")
					time.sleep(6.5)
					slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
					time.sleep(5)
					slow_type("\nHe put his camera down, smiled, and then just left.")
					time.sleep(6)
					slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
					time.sleep(4)
					slow_type2("\n.....")
					time.sleep(8.5)

			# new plot "introduction"

					if __name__ == "__main__":
					    print(".....")
					    time.sleep(3)
					    delete_last_line()

					# game starting
					answer = input(slow_type("Wake up...?: "))
					if answer.lower().strip() == "yes":
						slow_type2("\n.....")
						time.sleep(3)
						delete_last_line()
						slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
						time.sleep(2)
						slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
						time.sleep(3)
						slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
						time.sleep(5.5)
						slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
						time.sleep(3)
						slow_type2("\n.....")
						time.sleep(3)
						slow_type2("\nOh, my ex just texted me.")
						
						answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
						if answer== "yes" or answer == "no":
							slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
							time.sleep(7)
							slow_type("\nSuddenly, my door flew open.")
							time.sleep(2)
							slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
							time.sleep(3)
							slow_type("\n.....")
							time.sleep(3)
							slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
							time.sleep(3)
							slow_type2("\n'Who are you?! Why are you in my room?!'")
							time.sleep(4)
							slow_type2("\n???: Hey, don't cry!")
							time.sleep(3)
							slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
							time.sleep(4)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(2)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(5)
							slow_type("\n Hey.. why can't... I yell...?")
							time.sleep(2)
							slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
							time.sleep(4)
							slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
							time.sleep(5)
							slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
							time.sleep(5)
							slow_type("\nHe put his camera down, smiled, and then just left.")
							time.sleep(6)
							slow_type2("\n.....")
							time.sleep(8.5)

			# game "starting" again
							answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
							if answer == "yes" or answer == "no":
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
							else:
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")

					else:
						slowtype("I don't wanna wake up.. I'm scared...")
				
				else:
					slow_type("\nI wipe away my tears mid-photo and sit in silence. I feel too uncomfortable to speak.")
					time.sleep(3)
					slow_type("\nI can't get up. I can't stop crying. \nAnd all he's doing is taking my photograph..")
					time.sleep(6.5)
					slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
					time.sleep(5)
					slow_type("\nHe put his camera down, smiled, and then just left.")
					time.sleep(7)
					slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
					time.sleep(4)
					slow_type("\n.....")
					time.sleep(8.5)

			# new plot "introduction"

					if __name__ == "__main__":
					    print(".....")
					    time.sleep(3)
					    delete_last_line()

					# game starting
					answer = input(slow_type("Wake up...?: "))
					if answer.lower().strip() == "yes":
						slow_type2("\n.....")
						time.sleep(3)
						delete_last_line()
						slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
						time.sleep(2)
						slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
						time.sleep(3)
						slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
						time.sleep(5.5)
						slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
						time.sleep(3)
						slow_type2("\n.....")
						time.sleep(3)
						slow_type2("\nOh, my ex just texted me.")
						
						answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
						if answer== "yes" or answer == "no":
							slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
							time.sleep(7)
							slow_type("\nSuddenly, my door flew open.")
							time.sleep(2)
							slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
							time.sleep(3)
							slow_type("\n.....")
							time.sleep(3)
							slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
							time.sleep(3)
							slow_type2("\n'Who are you?! Why are you in my room?!'")
							time.sleep(4)
							slow_type2("\n???: Hey, don't cry!")
							time.sleep(3)
							slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
							time.sleep(4)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(2)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(5)
							slow_type("\n Hey.. why can't... I yell...?")
							time.sleep(2)
							slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
							time.sleep(4)
							slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
							time.sleep(5)
							slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
							time.sleep(5)
							slow_type("\nHe put his camera down, smiled, and then just left.")
							time.sleep(6)
							slow_type2("\n.....")
							time.sleep(8.5)

			# game "starting" again
							answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
							if answer == "yes" or answer == "no":
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
							else:
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
					
					else:
						slowtype("I don't wanna wake up.. I'm scared...")

		# 3a

			else:
				slow_type2("I wiped my tears away and listened to the voice from afar. I can hear him approaching, but I can't see him yet.")
				time.sleep(2)
				slow_type("\n\nA tall caucasian man emerged from the darkness of the Student Union Cafe and walked towards me, smiling. He held a Nikon camera in his hands and carried a big bright smile on his face. I don't recognize him, but then again, I've never really bothered trying to meet staff anyway. \nHe started to walk towards me, and then he stood in front of the giant windows in front of me.")
				time.sleep(3.5)
				slow_type2("\n???: Good girl!")
				time.sleep(2)
				slow_type("\nHe stared at me for a bit, and grinned brightly.")
				time.sleep(2)
				slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
				time.sleep(3)
				slow_type("\nAlthough he wiped the tears from my face, I felt more rushing out. Even though I started crying once again, he angled his camera down and took photos of me in every angle. I feel uncomfortable.")

				answer = input(slow_type("\nShould I... \n1-Ask him to stop. \n2-Ask him who he is. \n3-Ask him to help me up. \n")).lower().strip()
				if answer == '1' or answer == '2' or answer == '3':
					slow_type("\nI wipe away my tears mid-photo and open my mouth to ask him a question, but for some reason, I can't say anything at all.")
					time.sleep(3)
					slow_type("\nI can't get up. I can't talk. I can't stop crying. \nAnd all he's doing is taking my photograph..")
					time.sleep(6.5)
					slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
					time.sleep(5)
					slow_type("\nHe put his camera down, smiled, and then just left.")
					time.sleep(6)
					slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
					time.sleep(4)
					slow_type2("\n.....")
					time.sleep(8.5)

			# new plot "introduction"

					if __name__ == "__main__":
					    print(".....")
					    time.sleep(3)
					    delete_last_line()

					# game starting
					answer = input(slow_type("Wake up...?: "))
					if answer.lower().strip() == "yes":
						slow_type2("\n.....")
						time.sleep(3)
						delete_last_line()
						slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
						time.sleep(2)
						slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
						time.sleep(3)
						slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
						time.sleep(5.5)
						slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
						time.sleep(3)
						slow_type2("\n.....")
						time.sleep(3)
						slow_type2("\nOh, my ex just texted me.")
						
						answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
						if answer== "yes" or answer == "no":
							slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
							time.sleep(7)
							slow_type("\nSuddenly, my door flew open.")
							time.sleep(2)
							slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
							time.sleep(3)
							slow_type("\n.....")
							time.sleep(3)
							slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
							time.sleep(3)
							slow_type2("\n'Who are you?! Why are you in my room?!'")
							time.sleep(4)
							slow_type2("\n???: Hey, don't cry!")
							time.sleep(3)
							slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
							time.sleep(4)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(2)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(5)
							slow_type("\n Hey.. why can't... I yell...?")
							time.sleep(2)
							slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
							time.sleep(4)
							slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
							time.sleep(5)
							slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
							time.sleep(5)
							slow_type("\nHe put his camera down, smiled, and then just left.")
							time.sleep(6)
							slow_type2("\n.....")
							time.sleep(8.5)

			# game "starting" again
							answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
							if answer == "yes" or answer == "no":
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
							else:
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")

					else:
						slowtype("I don't wanna wake up.. I'm scared...")

				else:
					slow_type("\nI wipe away my tears mid-photo and sit in silence. I feel too uncomfortable to speak.")
					time.sleep(3)
					slow_type("\nI can't get up. I can't stop crying. \nAnd all he's doing is taking my photograph..")
					time.sleep(6.5)
					slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
					time.sleep(5)
					slow_type("\nHe put his camera down, smiled, and then just left.")
					time.sleep(7)
					slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
					time.sleep(4)
					slow_type("\n.....")
					time.sleep(8.5)
		# new plot "introduction"

					if __name__ == "__main__":
					    print(".....")
					    time.sleep(3)
					    delete_last_line()

		# game starting
					answer = input(slow_type("Wake up...?: "))
					if answer.lower().strip() == "yes":
						slow_type2("\n.....")
						time.sleep(3)
						delete_last_line()
						slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
						time.sleep(2)
						slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
						time.sleep(3)
						slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
						time.sleep(5.5)
						slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
						time.sleep(3)
						slow_type2("\n.....")
						time.sleep(3)
						slow_type2("\nOh, my ex just texted me.")
						
						answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
						if answer== "yes" or answer == "no":
							slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
							time.sleep(7)
							slow_type("\nSuddenly, my door flew open.")
							time.sleep(2)
							slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
							time.sleep(3)
							slow_type("\n.....")
							time.sleep(3)
							slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
							time.sleep(3)
							slow_type2("\n'Who are you?! Why are you in my room?!'")
							time.sleep(4)
							slow_type2("\n???: Hey, don't cry!")
							time.sleep(3)
							slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
							time.sleep(4)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(2)
							slow_type("\n(No, you fucking psycho!)")
							time.sleep(5)
							slow_type("\n Hey.. why can't... I yell...?")
							time.sleep(2)
							slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
							time.sleep(4)
							slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
							time.sleep(5)
							slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
							time.sleep(5)
							slow_type("\nHe put his camera down, smiled, and then just left.")
							time.sleep(6)
							slow_type2("\n.....")
							time.sleep(8.5)

			# game "starting" again
							answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
							if answer == "yes" or answer == "no":
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
							else:
								slow_type("\n???: Hey... wake up...")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
								time.sleep(4)
								slow_type("\n.")
					
					else:
						slowtype("I don't wanna wake up.. I'm scared...")

#path no.2

	if answer == "no":
		answer = input(slow_type("\nShould I get up? (Yes/No): ")).lower().strip()
		slow_type("My head still hurts though, so I can just rest here a bit longer.")
		time.sleep(4)
		slow_type2("\n.....")
		time.sleep(3)
		slow_type("\nThe moment I even started to get up from the couch, my legs gave out. It felt like someone was pushing down on my knees and not letting me get up. \nOh well, it's fine. My head hurts anyway and I just woke up so it's probably just the fact that I'm still pretty tired. I'll get up in a few mintues.\nLooking out at the large window panes, I immediately noticed one thing: the school was deserted. Usually there's random kids playing badminton in front of the building or a fundraiser happening-- especially if it's still bright out.. Where is everyone?")
		time.sleep(6)
		slow_type("\nI tried to get up once more, but I couldn't.")
		time.sleep(5)
		slow_type("\nI tried again, but I couldn't. \nThe sun has already started to set, and I can't get up.")
		time.sleep(4)
		slow_type2("\n'I just want to go home now.. Why can't I move..?' \nFeeling helpless, I bursted into tears. I couldn't find my phone or laptop or anything at all. I was trapped in school and I couldn't get up-- no one would be at school anymore.")
		time.sleep(4)
		slow_type("\n???: Hey.. don't cry!")
		time.sleep(4)
		slow_type("\nHuh..? Who was that?")
		time.sleep(4)
		slow_type("\nI can hear footsteps from far away getting closer...")
		time.sleep(2.5)

# sudden character interaction
		answer = input(slow_type("\nHuh..? Who is that.. What do I do..?\n1-Call for help! He could be one of the student advisors/security. \n2-Try to get up and hide. \n3-Stop crying.\n")).lower().strip()
		
		if answer== "1":
			slow_type2("\n'Help! I've been stuck here but I can't get up!'")
			slow_type("\nThe footsteps become louder and I can now see the man who told me to not cry. \nA tall caucasian man emerged from the darkness of the Student Union Cafe and walked towards me, smiling. He held a Nikon camera in his hands and carried a big bright smile on his face. I don't recognize him, but then again, I've never really bothered trying to meet staff anyway. \nHe started to walk towards me, and then he stood in front of the giant windows in front of me.")
			time.sleep(3.5)
			slow_type2("\n???: Ah I see.. But first...")
			time.sleep(2)
			slow_type("\nHe wiped away my tears and grinned brightly.")
			time.sleep(2)
			slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
			time.sleep(3)
			slow_type("\nAlthough he wiped the tears from my face, I felt more rushing out. Even though I started crying once again, he angled his camera down and took photos of me in every angle. I feel uncomfortable.")

			answer = input(slow_type("\nShould I... \n1-Ask him to stop. \n2-Ask him who he is. \n3-Ask him to help me up. \n")).lower().strip()
			if answer == '1' or answer == '2' or answer == '3':
				slow_type("\nI wipe away my tears mid-photo and open my mouth to ask him a question, but for some reason, I can't say anything at all.")
				time.sleep(3)
				slow_type("\nI can't get up. I can't talk. I can't stop crying. \nAnd all he's doing is taking my photograph..")
				time.sleep(6.5)
				slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
				time.sleep(5)
				slow_type("\nHe put his camera down, smiled, and then just left.")
				time.sleep(6)
				slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
				time.sleep(4)
				slow_type2("\n.....")
				time.sleep(8.5)

	# new plot "introduction"

				if __name__ == "__main__":
					print(".....")
					time.sleep(3)
					delete_last_line()

	# game starting
				answer = input(slow_type("Wake up...?: "))
				if answer.lower().strip() == "yes":
					slow_type2("\n.....")
					time.sleep(3)
					delete_last_line()
					slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
					time.sleep(2)
					slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
					time.sleep(3)
					slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
					time.sleep(5.5)
					slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
					time.sleep(3)
					slow_type2("\n.....")
					time.sleep(3)
					slow_type2("\nOh, my ex just texted me.")
						
					answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
					if answer== "yes" or answer == "no":
						slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
						time.sleep(7)
						slow_type("\nSuddenly, my door flew open.")
						time.sleep(2)
						slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
						time.sleep(3)
						slow_type("\n.....")
						time.sleep(3)
						slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
						time.sleep(3)
						slow_type2("\n'Who are you?! Why are you in my room?!'")
						time.sleep(4)
						slow_type2("\n???: Hey, don't cry!")
						time.sleep(3)
						slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
						time.sleep(4)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(2)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(5)
						slow_type("\n Hey.. why can't... I yell...?")
						time.sleep(2)
						slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
						time.sleep(4)
						slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
						time.sleep(5)
						slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
						time.sleep(5)
						slow_type("\nHe put his camera down, smiled, and then just left.")
						time.sleep(6)
						slow_type2("\n.....")
						time.sleep(8.5)

	# game "starting" again
						answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
						if answer == "yes" or answer == "no":
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
						else:
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")

				else:
					slowtype("I don't wanna wake up.. I'm scared...")
			
		if answer == "2":
			slow_type("I try once more to get up, but to no avail. The footsteps are already getting closer..")
			time.sleep(2)
			slow_type("\nA tall caucasian man emerged from the darkness of the Student Union Cafe and walked towards me, smiling. He held a Nikon camera in his hands and carried a big bright smile on his face. I don't recognize him, but then again, I've never really bothered trying to meet staff anyway. \nHe started to walk towards me, and then he stood in front of the giant windows in front of me.")
			time.sleep(3.5)
			slow_type2("\n???: Hey, what'd I say? Don't cry, smile!")
			time.sleep(2)
			slow_type("\nHe wiped away my tears and grinned brightly.")
			time.sleep(2)
			slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
			time.sleep(3)
			slow_type("\nAlthough he wiped the tears from my face, I felt more rushing out. Even though I started crying once again, he angled his camera down and took photos of me in every angle. I feel uncomfortable.")

			answer = input(slow_type("\nShould I... \n1-Ask him to stop. \n2-Ask him who he is. \n3-Ask him to help me up. \n")).lower().strip()
			if answer == '1' or answer == '2' or answer == '3':
				slow_type("\nI wipe away my tears mid-photo and open my mouth to ask him a question, but for some reason, I can't say anything at all.")
				time.sleep(3)
				slow_type("\nI can't get up. I can't talk. I can't stop crying. \nAnd all he's doing is taking my photograph..")
				time.sleep(6.5)
				slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
				time.sleep(5)
				slow_type("\nHe put his camera down, smiled, and then just left.")
				time.sleep(6)
				slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
				time.sleep(4)
				slow_type2("\n.....")
				time.sleep(8.5)

		# new plot "introduction"

				if __name__ == "__main__":
					print(".....")
					time.sleep(3)
					delete_last_line()

		# game starting
				answer = input(slow_type("Wake up...?: "))
				if answer.lower().strip() == "yes":
					slow_type2("\n.....")
					time.sleep(3)
					delete_last_line()
					slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
					time.sleep(2)
					slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
					time.sleep(3)
					slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
					time.sleep(5.5)
					slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
					time.sleep(3)
					slow_type2("\n.....")
					time.sleep(3)
					slow_type2("\nOh, my ex just texted me.")
						
					answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
					if answer== "yes" or answer == "no":
						slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
						time.sleep(7)
						slow_type("\nSuddenly, my door flew open.")
						time.sleep(2)
						slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
						time.sleep(3)
						slow_type("\n.....")
						time.sleep(3)
						slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
						time.sleep(3)
						slow_type2("\n'Who are you?! Why are you in my room?!'")
						time.sleep(4)
						slow_type2("\n???: Hey, don't cry!")
						time.sleep(3)
						slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
						time.sleep(4)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(2)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(5)
						slow_type("\n Hey.. why can't... I yell...?")
						time.sleep(2)
						slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
						time.sleep(4)
						slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
						time.sleep(5)
						slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
						time.sleep(5)
						slow_type("\nHe put his camera down, smiled, and then just left.")
						time.sleep(6)
						slow_type2("\n.....")
						time.sleep(8.5)

		# game "starting" again
						answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
						if answer == "yes" or answer == "no":
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
						else:
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type(".")
							time.sleep(4)
							slow_type("\n.")

				else:
					slowtype("I don't wanna wake up.. I'm scared...")
				
			else:
				slow_type("\nI wipe away my tears mid-photo and sit in silence. I feel too uncomfortable to speak.")
				time.sleep(3)
				slow_type("\nI can't get up. I can't stop crying. \nAnd all he's doing is taking my photograph..")
				time.sleep(6.5)
				slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
				time.sleep(5)
				slow_type("\nHe put his camera down, smiled, and then just left.")
				time.sleep(7)
				slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
				time.sleep(4)
				slow_type("\n.....")
				time.sleep(8.5)

	# new plot "introduction"

				if __name__ == "__main__":
				    print(".....")
				    time.sleep(3)
				    delete_last_line()

		# game starting
				answer = input(slow_type("Wake up...?: "))
				if answer.lower().strip() == "yes":
					slow_type2("\n.....")
					time.sleep(3)
					delete_last_line()
					slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
					time.sleep(2)
					slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
					time.sleep(3)
					slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
					time.sleep(5.5)
					slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
					time.sleep(3)
					slow_type2("\n.....")
					time.sleep(3)
					slow_type2("\nOh, my ex just texted me.")
						
					answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
					if answer== "yes" or answer == "no":
						slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
						time.sleep(7)
						slow_type("\nSuddenly, my door flew open.")
						time.sleep(2)
						slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
						time.sleep(3)
						slow_type("\n.....")
						time.sleep(3)
						slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
						time.sleep(3)
						slow_type2("\n'Who are you?! Why are you in my room?!'")
						time.sleep(4)
						slow_type2("\n???: Hey, don't cry!")
						time.sleep(3)
						slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
						time.sleep(4)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(2)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(5)
						slow_type("\n Hey.. why can't... I yell...?")
						time.sleep(2)
						slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
						time.sleep(4)
						slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
						time.sleep(5)
						slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
						time.sleep(5)
						slow_type("\nHe put his camera down, smiled, and then just left.")
						time.sleep(6)
						slow_type2("\n.....")
						time.sleep(8.5)

			# game "starting" again
						answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
						if answer == "yes" or answer == "no":
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
						else:
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")

				else:
					slowtype("I don't wanna wake up.. I'm scared...")

		else:
			slow_type2("I wiped my tears away and listened to the voice from afar. I can hear him approaching, but I can't see him yet.")
			time.sleep(2)
			slow_type("\n\nA tall caucasian man emerged from the darkness of the Student Union Cafe and walked towards me, smiling. He held a Nikon camera in his hands and carried a big bright smile on his face. I don't recognize him, but then again, I've never really bothered trying to meet staff anyway. \nHe started to walk towards me, and then he stood in front of the giant windows in front of me.")
			time.sleep(3.5)
			slow_type2("\n???: Good girl!")
			time.sleep(2)
			slow_type("\nHe stared at me for a bit, and grinned brightly.")
			time.sleep(2)
			slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
			time.sleep(3)
			slow_type("\nAlthough he wiped the tears from my face, I felt more rushing out. Even though I started crying once again, he angled his camera down and took photos of me in every angle. I feel uncomfortable.")

			answer = input(slow_type("\nShould I... \n1-Ask him to stop. \n2-Ask him who he is. \n3-Ask him to help me up. \n")).lower().strip()
			if answer == '1' or answer == '2' or answer == '3':
				slow_type("\nI wipe away my tears mid-photo and open my mouth to ask him a question, but for some reason, I can't say anything at all.")
				time.sleep(3)
				slow_type("\nI can't get up. I can't talk. I can't stop crying. \nAnd all he's doing is taking my photograph..")
				time.sleep(6.5)
				slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
				time.sleep(5)
				slow_type("\nHe put his camera down, smiled, and then just left.")
				time.sleep(6)
				slow_type("\nI was alone again. I tried to call out to him, but I still couldn't speak or move.")
				time.sleep(4)
				slow_type2("\n.....")
				time.sleep(8.5)

	# new plot "introduction"

				if __name__ == "__main__":
				    print(".....")
				    time.sleep(3)
				    delete_last_line()

		# game starting
				answer = input(slow_type("Wake up...?: "))
				if answer.lower().strip() == "yes":
					slow_type2("\n.....")
					time.sleep(3)
					delete_last_line()
					slow_type2("\nI jolted up from my bed and woke up utterly fucking terrified. \nIs that what it feels like to be paralyzed...?")
					time.sleep(2)
					slow_type("\nI looked around the room and thank goodness, it was my room. It felt good to be home again, but damn did that dream feel real. \nI picked up my phone to check the time and read '6:45 AM.' \nDamn, I actually woke up before my alarm for once? \n")
					time.sleep(3)
					slow_type2("\nGuess this means I finally get to eat breakfast before school for once!")
					time.sleep(5.5)
					slow_type2("\n..... My legs fell asleep \nI don't like how it feels when I try to walk when my legs are asleep-- last time I tried to, I fell in front of a Michael's.")
					time.sleep(3)
					slow_type2("\n.....")
					time.sleep(3)
					slow_type2("\nOh, my ex just texted me.")
					
					answer = input(slow_type("\nShould I text him back?: \n")).lower().strip()
					if answer== "yes" or answer == "no":
						slow_type2("\nOh fuck it! I miss him anyway. \nHonestly, mid-conversation, I started crying tears of joy because he said he wanted to get back together!! I get to see him at school too!! ")
						time.sleep(7)
						slow_type("\nSuddenly, my door flew open.")
						time.sleep(2)
						slow_type2("\n'troi oi, tai sao ba khong go cua truoc?! (translation: oh my gosh dad, why can't you knock first?!)' \nI frantically started to wipe away my tears, but I was still too overwhelmed by the current text conversation I was having. ")
						time.sleep(3)
						slow_type("\n.....")
						time.sleep(3)
						slow_type("\nNo response.\nAnnoyed, I turned over, facing the door and saw the same tall, caucasian man with the camera. \nWhat the fuck is going on?")
						time.sleep(3)
						slow_type2("\n'Who are you?! Why are you in my room?!'")
						time.sleep(4)
						slow_type2("\n???: Hey, don't cry!")
						time.sleep(3)
						slow_type2("\n???: Pretty girls shouldn't cry. Why don't you smile for me?")
						time.sleep(4)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(2)
						slow_type("\n(No, you fucking psycho!)")
						time.sleep(5)
						slow_type("\n Hey.. why can't... I yell...?")
						time.sleep(2)
						slow_type("\nHe angled his camera down and took photos of me in every angle. \nI'm unable to move or speak once again, and instead of uncomfortable, I'm afraid. \nWhy is this nightmare coming true..?")
						time.sleep(4)
						slow_type("\nWait.. He looks.. slightly different than he did in the dream. \nUpon closer observation, I noticed that his smile was slightly different.. It was still bright and big, but it was comically upturned. \nI felt chills going down my spine looking at this man. He didn't even... look like a man...")
						time.sleep(5)
						slow_type2("\n???: You're beautiful. Don't cry, it'll mess up your pretty face.")
						time.sleep(5)
						slow_type("\nHe put his camera down, smiled, and then just left.")
						time.sleep(6)
						slow_type2("\n.....")
						time.sleep(8.5)

		# game "starting" again
						answer = input(slow_type("\nWake up...for sure this time?: ")).lower().strip()
						if answer == "yes" or answer == "no":
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
						else:
							slow_type("\n???: Hey... wake up...")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
							time.sleep(4)
							slow_type("\n.")
						
				else:
					slowtype("I don't wanna wake up.. I'm scared...")
# game end
if answer.lower().strip() == "no":			
	slow_type("\nThere's a throbbing pain on the left side of my head.. maybe I'll just sleep for longer.")